apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: browser

resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: gh-chrome
    includeSelectors: true
