apiVersion: v1
kind: Service
metadata:
  name: gh-chrome
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: gh-chrome
  ports:
    - name: http
      port: 8001
      targetPort: http
      nodePort: 30084
      protocol: TCP
