apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: browser

resources:
- migrate.yaml
- server.yaml
- relay.yaml
- fleet.yaml
- service.yaml

images:
- digest: sha256:93460f6c99e506a0aca8420fb86a330a2f0c6840fd25c9f1564f027bb853de05
  name: ghcr.io/wprhvso/gh-pool
  newName: ghcr.io/wprhvso/gh-pool
  newTag: 0.1.6

labels:
- pairs:
    app.kubernetes.io/part-of: gh-pool
