name: ci

on:
  push:

jobs:
  ruff:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: ruff check --output-format github .

  format:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: ruff format --check --diff .

  pyright:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: uv sync --frozen
      - run: basedpyright

  unit:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: uv sync --frozen
      - run: pytest --ignore=tests/chrome/e2e --ignore=tests/test_e2e.py

  e2e:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: uv sync --frozen
      - run: pytest tests/chrome/e2e tests/test_e2e.py
