name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  pytest:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: wprhvso/qa-python@v1
        with:
          checks: pytest

  shell:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: wprhvso/qa-shell@v1
